### ISSUE TITLE
Code incomplete?

### ISSUE THREAD

**Issue by bestware** [HugoSilvaSantos/Self_Balancing_Robot#2]
Code looks strange and incomplete!
## This part doesn't handle all positions:

Set the vertical mass center

```
pwm_adjust(corrected_y);
if(corrected_y>-50 && corrected_y<-18){
    backward();    
}else if(corrected_y>=-15 && corrected_y<0){
    forward();          
}else{
    stop();
}
```

---

corrected_y values between -18..-15 or > 0 leading to stop. Is this intended?

rgds.

bestware

**Comment by HugoSilvaSantos** [comment]
The purpose of that code snippet is to set the vertical mass centre. That was adjusted specifically for my SBR, and should vary to another implementations. However code snippet could/should be optimized.

Cheers, Hugo.

**Comment by bestware** [comment]
I see - thank you, Hugo!
